version: "3.8"

services:
  shopware:
    image: ghcr.io/namainchick/test_shopware:latest
    container_name: test_shop_prod
    ports:
      - "8080:80"
      - "8443:443"
      - "1081:1080"
      - "9091:9090"
    volumes:
      - shop_data:/var/www/html
    environment:
      - XDEBUG_ENABLED=0
    restart: unless-stopped
    networks:
      - shopware

volumes:
  shop_data:

networks:
  shopware:
