version: "3.8"

services:
  shopware:
    image: dockware/dev:latest
    container_name: test_shop
    ports:
      - "80:80"
      - "443:443"
      - "1080:1080"
      - "9090:9090"
      - "8888:8888"
      - "22:22"
    volumes:
      - ./src:/var/www/html
    environment:
      - XDEBUG_ENABLED=0
    networks:
      - shopware

networks:
  shopware:
